version: "3.9"

services:
  # Serviço do django para rodar o projeto
  django_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/container"
    ports:
      - "8000:8000"
