# Generated by Django 4.1.3 on 2022-12-05 00:25

from django.db import migrations, models
import manager.models.produtos


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=manager.models.produtos.upload_to_path)),
            ],
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagens',
            field=models.ManyToManyField(blank=True, related_name='produto', to='manager.produtoimagem'),
        ),
    ]
