# Generated by Django 4.1.3 on 2022-12-18 19:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, db_index=True, default='', max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('tipo', models.CharField(choices=[('P', 'Porcentagem'), ('V', 'Valor')], max_length=1)),
                ('retorno', models.CharField(choices=[('P', 'Promoção'), ('C', 'Cupom')], db_index=True, max_length=1)),
                ('inicio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fim', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDescontoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidodesconto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.pedidodesconto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.produto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='manager.pedidodescontoproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manager.produto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDescontoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidodesconto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.pedidodesconto')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.tag')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDescontoSubcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidodesconto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.pedidodesconto')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDescontoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.categoria')),
                ('pedidodesconto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.pedidodesconto')),
            ],
        ),
        migrations.AddField(
            model_name='pedidodesconto',
            name='categorias',
            field=models.ManyToManyField(through='manager.PedidoDescontoCategoria', to='manager.categoria'),
        ),
        migrations.AddField(
            model_name='pedidodesconto',
            name='produtos',
            field=models.ManyToManyField(through='manager.PedidoDescontoProduto', to='manager.produto'),
        ),
        migrations.AddField(
            model_name='pedidodesconto',
            name='subcategorias',
            field=models.ManyToManyField(through='manager.PedidoDescontoSubcategoria', to='manager.subcategoria'),
        ),
        migrations.AddField(
            model_name='pedidodesconto',
            name='tags',
            field=models.ManyToManyField(through='manager.PedidoDescontoTag', to='manager.tag'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado'), ('S', 'Estornado'), ('E', 'Entregue')], max_length=1)),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.pedidodesconto')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itens', models.ManyToManyField(to='manager.pedidoitem')),
            ],
        ),
    ]
