# Generated by Django 4.1.4 on 2022-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_rename_dono_pedido_user_alter_pedido_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
