# Generated by Django 4.1.3 on 2022-12-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_produtoimagem_rename_imagem_produto_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slogan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
