# Generated by Django 4.1.3 on 2022-12-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_categoria_created_at_categoria_mostrar_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pedidodesconto',
            name='subcategorias',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='PedidoDescontoSubcategoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(to='manager.categoria'),
        ),
    ]
