# Generated by Django 4.1.4 on 2022-12-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_alter_carrinhoitem_index_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoitem",
            name="cupom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pedidos_cupons",
                to="manager.pedidodesconto",
            ),
        ),
        migrations.AlterField(
            model_name="pedidodesconto",
            name="categorias",
            field=models.ManyToManyField(blank=True, to="manager.categoria"),
        ),
        migrations.AlterField(
            model_name="pedidodesconto",
            name="produtos",
            field=models.ManyToManyField(blank=True, to="manager.produto"),
        ),
        migrations.AlterField(
            model_name="pedidodesconto",
            name="tags",
            field=models.ManyToManyField(blank=True, to="manager.tag"),
        ),
        migrations.AlterField(
            model_name="pedidoitem",
            name="desconto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pedidos_descontos",
                to="manager.pedidodesconto",
            ),
        ),
    ]
