# Generated by Django 4.1.3 on 2022-12-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_subcategoria_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
