# Generated by Django 4.1.3 on 2022-12-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_produto_data_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
    ]
